import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars : SidebarsConfig = {
    blogAsDocSidebar: [
        // {   
        //     type: 'autogenerated', 
        //     dirName: '.'
        // },
        {
            type: 'category',
            label: 'Spectrometer GUI',
            link: {
              type: 'generated-index',
            },
            collapsed: true,
            items: [
              'Spectrometer GUI/introduction',
              'Spectrometer GUI/appbar',
            ],
          },
    ],

    // https://docusaurus.io/docs/sidebar
};

export default sidebars;
